spring.application.name=hrtool
# Server
server.port=8089

# HRTool
hrtool.secretkey = 6C697A5F467A736B5A644D635166546A576E5A7234753778214125442A472D4B
hrtool.cors.cideonip = hrtool.cideng.net
#5h in seconds
hrtool.refreshToken.maxAge = 18000
#15min in seconds
hrtool.accessToken.maxAge = 900
#rabbitMQRoutes
hrtool.rabbitmq.ExchangeName = backendExchange
hrtool.rabbitmq.RoutingKey.publishNewAccount = account.create
hrtool.rabbitmq.RoutingKey.publishChangePassword = account.changePassword

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hrtool
#spring.datasource.url=jdbc:postgresql://HR_DB:5432/hrtool
#spring.datasource.url=jdbc:postgresql://hrPostgres:5432/hrtool
#spring.datasource.url=jdbc:postgresql://host.containers.internal:5432/hrtool
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Jackson (format JSON)
spring.jackson.serialization.indent_output=true


spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

# spring.web.cors.allowed-origins=http://localhost:4200
# spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
#
#spring.sql.init.mode=always
#spring.datasource.initialization-mode=always

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.security=DEBUG

#RabbitMQ
spring.rabbitmq.host=localhost
#spring.rabbitmq.host=rabbitMQ
spring.rabbitmq.username=hrBackend
spring.rabbitmq.password=pw
spring.rabbitmq.port=5672
#spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.auto-startup=false
spring.rabbitmq.listener.direct.auto-startup=false
app.rabbit.enabled=false